#pragma once

// Increase debounce from the default 20.
#undef DEBOUNCE
#define DEBOUNCE 30

#define MOUSEKEY_INERTIA

#undef MOUSEKEY_DELAY
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_FRICTION
#undef MOUSEKEY_MOVE_DELTA

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_TIME_TO_MAX 24
#define MOUSEKEY_FRICTION 48
#define MOUSEKEY_MOVE_DELTA 1
